### ISSUE TITLE
使用编译版本时，用 branch name 替代 DEBUG VERSION

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10874]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

**Comment by Constrat** [comment]
Wouldn't this require changing quite a lot of code? iirc, the current logic doesn't give a shit about what is happening in git, as it's all managed by VS itself.

**Comment by status102** [comment]
感觉没啥意义

**Comment by Constrat** [comment]
Yes, honestly I don't feel the utility. I'll explain myself.

The DEBUG VERSION only appears if you send a screenshot, so from a user perspective it's useless since users will never build MAA from themselves and if they did, having the branch name wouldn't give us much utility.

MAA works on a single branch, meaning that we don't distribute different forks and branches, so the eventual debug version, would just be `dev` in most cases.

And even in a PR environment between us devs, having the debug version a different name wouldn't be that much useful since you would just need to check the branch name anyway in github.

**Comment by Alan-Charred** [comment]
This sounds like someone is going to keep a bunch of MAA debug builds at the same time... which is a situation I have not met with yet.
If you are going to do it in your own repo, check the `CMakeLists.txt` file.

```CMake
# define MAA_VERSION from git
if (NOT DEFINED MAA_VERSION)
    find_package(Git)
endif ()
if (NOT DEFINED MAA_VERSION AND GIT_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE err
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if (result EQUAL 0)
        set(MAA_VERSION "${output}")
    else ()
        message(WARNING "git rev-parse returning ${result}, output:\n${err}")
    endif ()
endif ()
if (NOT MAA_VERSION)
    set(MAA_VERSION "DEBUG VERSION")
endif ()
message(STATUS "MAA_VERSION=${MAA_VERSION}")
add_compile_definitions(MAA_VERSION="${MAA_VERSION}")
```

I am not an expert in this, but I guess you can manipulate this to achieve what you want.

**Comment by Constrat** [comment]
Yes that's my point, implementing a CMAKE that uses the git branch is probably not ideal for everyone.
