### ISSUE TITLE
碎石的博朗台模式已经失去效果

### ISSUE THREAD

**Issue by xiao-MC666** [MaaAssistantArknights/MaaAssistantArknights#11048]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

碎石的博朗台模式已经失去效果，且会产生无效地等待时间。

### 有什么好的想法？

建议删除该用途或者隐藏开关

### 其他内容

无

**Comment by status102** [comment]
存在溢出风险，等待优化

**Comment by Constrat** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/11140#issuecomment-2470280994

Bringing the answer / thought here from #11140:

Isn't this just a coincidence in numbers?
You are at 15 sanity, and the potion gives 120, for a total of 135: coincidentally the older sanity cap
You could have been at 0 sanity and the potion giving just 80 (monthly) and it would have still waited.

DrGrandet mode doesn't care about the reaching sanity value, it's just a simple algorithm that chooses to use sanity (whatever value) after the sanity changes by one point.

If you check the source code, you'll notice that the algorithm is run every time MAA tries to use a potion, because we consider it worst case scenario every time aka, you are breaching the sanity cap with 120 potions.

In a way you are right though.
With the new 180 cap, breaching the sanity is basically impossible now with one potion at a time.

The biggest stages are the chip stages that cost 36 sanity. The biggest potion is just 120 sanity. Meaning a total of 156 which is well below the new limit.
