### ISSUE TITLE
能不能在抄作业的时候，编队识别不到人的时候，超过一定次数停止当前任务

### ISSUE THREAD

**Issue by Lancarus** [MaaAssistantArknights/MaaAssistantArknights#6001]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

睡觉之前开了抄小剿灭的作业睡觉了，醒来发现maa还在划动找人
asst.log有100m了。。
![Y`PG%RRH%@QP0SPQEP2VN7S](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/cc867809-45ae-4798-9a53-7579afe36c1e)
![`6{HOM}ZSVT8TQ`6CH4E}{7](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/ae905c61-6fb1-470e-9996-b7facccff478)

### 有什么好的想法？

回头也方便加个根据找不到的人数自动借干员的功能（画饼）

**Comment by Lancarus** [comment]
#5934 看了一下是找不到纯爱

**Comment by Constrat** [comment]
How many chars are you able to detect?
.*烬艾雅法拉 this should work. If not: removing one more char is difficult because it only leaves 艾雅法拉 which is just Eyjafjalla

**Comment by Lancarus** [comment]
> How many chars are you able to detect? .*烬艾雅法拉 this should work. If not: removing one more char is difficult because it only leaves 艾雅法拉 which is just Eyjafjalla

no one。。。i don‘t know how it‘s ocr works，but there is no char show in the log.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/c7438884-0ab8-4670-a1e7-e39686abb57d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/8e5cf067-a97c-409e-ba47-46e10fe18bc3)

**Comment by Constrat** [comment]
I'll try and have a look at it. I think I should have Eyja alter in the CN.

**Comment by Lancarus** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/9a7e46cf-64c6-4650-81fc-ef291f72cd6b)
sorry, i show the wrong picture, here is the error location. it recognized nothing...

**Comment by Constrat** [comment]
The problem is the multi_match_template | BattleQuickFormstion-OperNameFlag result.
If it's can't find the lower left corner of the operator icon "free" it won't have a correct rect for name detection. Could you send the entire 2624 line?

**Comment by Lancarus** [comment]
[2023-08-20 12:48:03.082][TRC][Px4a3c][Tx2b80] multi_match_templ |  BattleQuickFormation-OperNameFlag.png result: [{ rect: [ 959, 326, 12, 20 ], score: 0.986761 }, { rect: [ 624, 386, 12, 20 ], score: 0.929473 }, { rect: [ 959, 603, 12, 20 ], score: 0.981508 }] roi: [ 370, 250, 715, 420 ]

im in  1920x1080

**Comment by Constrat** [comment]
@MistEO Trying to debug this:
I've noticed that the OperBox 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/9bf40519-b428-49dd-8025-97a39ec66a4e)
detection now uses the operator role as anchor to detect text instead of the bottom left corner (seems more reliable) With this, Eyjafjalla Alter gets detected correctly even on the bottom row.
The main difference between the Operators and the Squads operbox tabs are that the oper names are a bit larger (also the level). So the "old" `BattleQuickFormation-OperNameFlag.png` has even more issues considering it was took from the Operators tab. The crazy thing is: it would be better to use the new `multi_match_templ |  OperBoxFlagRoleX.png` in the Auto Squad quick select operations than in the Toolbox/Operators.
