### ISSUE TITLE
MISSING CLOSE GUIDE TEMPLATE; IS3 Abandonment Loop in YostarEN

### ISSUE THREAD

**Issue by whayatosan** [MaaAssistantArknights/MaaAssistantArknights#6281]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Hello,

Good day. I am posting an abnormality from using the AutoIS feature with Mizuki option. Somehow it loops from starting a run and then immediately abandoning it. Kindly see attachment for reference.

Regards,

### Log files

/
[asst.log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12564561/asst.log.txt)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12564562/gui.log)

### Screenshots

![image-112](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140710898/b4ade1b2-d1f0-4bbe-bfc8-d6e672426807)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/080900cf-43b7-44cb-8e9b-be1c888d310b)

**Comment by whayatosan** [comment]
Hi,

Thank you for pointing that out. Apologies for the mistake. Yes, that's for IS2.

Kindly see attachment below is for the IS3 one and different client. I'm not able to produce a screenshot because I have it closed.
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12564636/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12564640/asst.log)

Regards,

**Comment by Constrat** [comment]
I'm having troubles understanding...
The issue is with Phantom or Mizuki? Because i'm checking our latest asst.log and I can't find 2023-09-09 03:04:59.486, and everything looks working.

**Comment by Constrat** [comment]
Looking at the FIRST asst.log.txt, the issue is defintely using the Phantom template in the Mizuki IS:
```
[2023-09-09 11:53:14.006][TRC][Px5148][Tx7790] asst::PipelineAnalyzer::analyze Phantom@Roguelike@MissionFailedFlag2
[2023-09-09 11:53:14.013][TRC][Px5148][Tx7790] asst::PipelineAnalyzer::analyze Phantom@Roguelike@StartExplore
[2023-09-09 11:53:14.018][TRC][Px5148][Tx7790] asst::ProcessTask::_run | leave, 356 ms
```
It can't detect Mizuki's because it's trying with Phantom's templates

**Comment by whayatosan** [comment]
Hi,

Thanks for responding. This date is found in the attachment in the follow-up comment I posted under gui.log.

`[2023-09-09 03:04:59.486] <1><> Start task: Roguelike
[2023-09-09 03:05:16.844] <1><> Exploration started 1 times
[2023-09-09 03:06:08.324] <1><> Abandoned this Exploration
[2023-09-09 03:06:18.100] <1><> Exploration started 2 times
[2023-09-09 03:07:08.718] <1><> Abandoned this Exploration
[2023-09-09 03:07:20.421] <1><> Exploration started 3 times
[2023-09-09 03:08:09.028] <1><> Abandoned this Exploration`

this looped 100 times before saying task is completed.

**Comment by Constrat** [comment]
Ok but... I have no asst.log of that date, without asst.log there is nothing I can do. In this case, gui.log is a bit useless

**Comment by whayatosan** [comment]
Hi,

I found a backup asst.bak.log with the date and time stamp. But this is 200MB for some reason.

I am posting a .txt file below with the portion of the log from the time it showed the error from gui.log.

[asst_2023-09-09 030459.486.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12565410/asst_2023-09-09.030459.486.txt)

**Comment by Constrat** [comment]
Ok, I'm fixing right now:
What happens: you might have a fresh install. So the first time you enter the I.S. it starts the "tutorial" I still hadn't adapted that part, so we have a missing template:
```
[2023-09-09 03:05:44.602][TRC][Px2548][Tx7500] match_templ | Roguelike@ChooseOperConfirm.png score: 0.76482 rect: [ 1066, 653, 191, 49 ] roi: [ 1016, 602, 264, 118 ]
[2023-09-09 03:05:44.602][TRC][Px2548][Tx7500] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@RecruitCloseGuide
[2023-09-09 03:05:44.604][TRC][Px2548][Tx7500] asst::ProcessTask::_run | leave, 614 ms
```
Give me a bit of time to create the new template.

**Comment by whayatosan** [comment]
Thank you.

Sincere apologies for causing confusion.

**Comment by Constrat** [comment]
No confusion at all, the more we fix, the better it is for everyone

**Comment by migavhub** [comment]
Hello! First off~ Thank you for addressing this concern. For full disclosure and to clear up any confusion, my friend (thread starter) uploaded both our clients' logs as we were having similar problems, albeit for different IS contents. The first ones he uploaded were mine where I was trying to run IS2, which is why IS2 is what was shown in the logs.

I've tried a fresh install of MAA and updated it with the nightly release. After updating the client, I am still experiencing an abandonment loop for IS2. The client detects everything and works fine until it reaches to the point where it has to pick a starting operator and then just abandons the run after a few seconds of not doing anything.

Here are the screenshots and logs from the newly installed and updated client:

**Screenshot:**
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144572337/d475ca44-0921-4621-8fb8-089a6706cff9)
![2023-09-10_10-05-20-514_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144572337/aa804d6e-388f-4d9c-9ec4-d6ff967a624d)


**Logs:**
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567034/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567035/asst.log)

**Comment by Constrat** [comment]
Ok we just have a threshold issue. Nothing complicated.
