### ISSUE TITLE
繁中服保全派駐无法执行

### ISSUE THREAD

**Issue by meikenakinori** [MaaAssistantArknights/MaaAssistantArknights#7029]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

繁中服保全派驻自动站斗, 兩個作业（阿卡胡拉，多索雷斯）开始时提示Recognition error or JSON does not support this, 并退出
mma 穩定版

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062381/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062382/asst.log)

**Comment by lianggexp** [comment]
遇到同样的情况。
问题补充：
尝试把json当中的"stage_name"改为繁体中文，运行时不再提示“Recognition error ”，且可以进入关卡，但紧接着立即提示“不支持的关卡，请检查关卡名”，无法继续执行作战。

日志文件：
[SSS_阿卡胡拉丛林TW.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062422/SSS_.TW.json)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062423/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062424/gui.log)

截图：
<img width="743" alt="屏幕截图 2023-10-22 130622" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11556949/dd85e6ab-1c6c-45eb-8513-e69a7e1f35ed">

**Comment by Constrat** [comment]
You are both using MAA v4.25.0 it's pretty much obvious it won't work. That version still does not support the stages.
A PR has been merged yesterday to implement the SSS stages:
- #7021

I'm releasing an alpha version so that you can try if it works. Give GitHub Actions ~25 minutes, then update MAA 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/a207554f-0308-4497-8ff8-6ad7f4b5c246) from where. (Make sure it's Nightly)

**Comment by Constrat** [comment]
fixed with 
- #7021
- [776f27c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/776f27ccc5fa3284af20519835fd3c8e4433a57e)
