### ISSUE TITLE
希望可以增加一些便于全自动托管的功能

### ISSUE THREAD

**Issue by 2023899320** [MaaAssistantArknights/MaaAssistantArknights#7110]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我是在校住宿生，基本上一周只有周六日能接触电子设备，平时舟都是让电脑定时启动然后maa托管。这是我遇到的一些问题

### 有什么好的想法？

1.新客户端更新问题：希望增加自动更新客户端的功能
2.限定池每日免费一抽：希望增加每日自动抽卡功能
3.限定池开放期间每日免费合成玉问题：希望maa可以自动领取

### 其他内容

谢谢开发者们

**Comment by status102** [comment]
1和23差好远，最好还是分开提issue

**Comment by zzyyyl** [comment]
自动更新客户端已经有了吧

**Comment by Constrat** [comment]
@zzyyyl 
Auto update of the client would go outside of what MaaAssistantArknights is supposed to do no?
Also because of the different type of update options: official website, play store, downloading apk from external site
(Also depending on the Emulator version / type some apk are allowed / not allowed) This seems like a HUGE trouble just for something that happens usually once a month.

**Comment by SherkeyXD** [comment]
干脆做个 Maa Updater 得了（

**Comment by 2023899320** [comment]
主要是希望能全自动

**Comment by SherkeyXD** [comment]
升级不好实现的 外服的客户端很多没有直链下载，得上应用商店下
