### ISSUE TITLE
请求添加一个“设定好干员专精列表，MAA自动点开专精室合成材料专精技能，且可以按时间启动”的功能

### ISSUE THREAD

**Issue by github123520** [MaaAssistantArknights/MaaAssistantArknights#7293]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Constrat** [comment]
This is already planned. 
Opening Enhancement proposal without a basic coding idea is not very useful.
We already have lots of ideas to add but still no way to implement them because of complexity/ lack of manpower. If you already have algorithms/structures/tasks etc you are very welcome to let us know, but just giving the idea is not much.
