### ISSUE TITLE
希望肉鸽能出一个当前战斗设置暂停

### ISSUE THREAD

**Issue by LingYuYo** [MaaAssistantArknights/MaaAssistantArknights#7326]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

打肉鸽的时候出问题，maa一直再跟我抢鼠标和干员

### 有什么好的想法？

处于关卡内 开始按钮能切换等待结束而非依旧是停止，如果已经有这个功能的话，我不知道为什么在战斗中无法暂停，哪怕我已经按了一次停止之后，他依旧会抢鼠标
见谅，有点表述不清晰。

**Comment by Constrat** [comment]
If you press "Stop" MAA will stop executing, unless there's a deadlock / crash / error, in that case it's a different thing.
"Pausing" in I.S. is already half implemented. If you finish a fight and STOP MAA, leave and do something else. You can come back later when the I.S. is in the level map and MAA will start again from where it was. IIRC it won't be as efficient as a single run, because he won't remember the relics / operators used / paths etc... But a "pause" kind of exists. 
Marking as resolved
