### ISSUE TITLE
多MAA识别资源文件复用

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#7388]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

按照MAA多开建议，需要将maa文件夹复制多份，此时资源文件(\resource\)(178 MB)也会被复制多份，

### 有什么好的想法？

是否能够将此文件夹独立出来给全部maa公用

**Comment by Constrat** [comment]
This would be much more complex because it would mean either
- creating master MAA with the resources and a slave MAA without the resources to make it scalable
- somehow putting the resource in a parent directory and placing all the MAA instances in a subfolder. But this would means changing pretty much everything and obligating users to implement this strange folder structure.
IMHO, not worth the time.

**Comment by zzyyyl** [comment]
也许你可以考虑建符号链接（？

**Comment by KJH-x** [comment]
> This would be much more complex because it would mean either
> 
> * creating master MAA with the resources and a slave MAA without the resources to make it scalable
> * somehow putting the resource in a parent directory and placing all the MAA instances in a subfolder. But this would means changing pretty much everything and obligating users to implement this strange folder structure.
>   IMHO, not worth the time.

You are right, before I post this issue I’ve thought about these problems. Yet I still wonder if there is better solution.

> 也许你可以考虑建符号链接（？

是的，我原本有计划这样做，但考虑到自己懂得不多，故来问问有没有更好的办法，近几天可能会尝试符号链接，相关情况会在这篇issue下反馈。

**Comment by KJH-x** [comment]
省流：符号链接*能用*

详细操作记录：
在Windows 10 专业版 22H2 19045.3324，Maa 4.27.0
- 将resource文件夹中内容复制并移动到public_resource
- 删除resource文件夹
- 使用pwsh 7.3.9 (管理员)执行：
```powershell
New-Item -ItemType SymbolicLink -Path "…\maa\resource" -Target "…\public_resource"
```
- 对于多个maa文件夹执行上述链接建立
- 同时运行两个maa未见异常。

> 注意：本次测试可能未体现以下问题/潜在风险：
> - 资源热更新多maa同时读写同文件
> - maa大更新时文件写入
> - 其他未考虑到的问题
