### ISSUE TITLE
Maintaining consistent state of 'Base Plan' option across configs

### ISSUE THREAD

**Issue by NyanSequitur** [MaaAssistantArknights/MaaAssistantArknights#8412]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

My base runs on a 36 hour cycle, so I can't use the time of day to determine which base formation to use. MAA is scheduled every 3 hours because I'm terminally online, and I tried having three configs:
- Reset
- Non-reset (no base)
- Non-reset (base)

Since there are some tasks like the credit store that don't need to be automatically run more than once a day. The problem is when Reset finishes updating the base and selects the next base plan, it doesn't update Non-reset (base)'s next base plan, leading to the base not changing correctly.

### Any good ideas?

- Option to sync the next base plan to use across configs
- Support for time-based multi-day base cycles.
  -  First thought is that each plan gets an (optional) day field alongside the period, and the plan is only used if `day == (unix_time//86400)%days_in_cycle` is true (I realize this means I would need to duplicate my plan from 36->72 hours, but that's not a big deal)

**Comment by Constrat** [comment]
I'm sorry but there's something I can't understand about this.
You have a 36 hrs cycle and as you said you can't use the clock timings, as MAA allows only MAX 24 hours base plans.
If no time is set, MAA will execute the `next` shift change the next time it gets run. 
Your problem is that you don't want to run all the other tasks every time? Especially the credit store fight?

- credit store fight is only done once a day as you can see, so it won't uselessly run every other time.
   ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/ea3d3576-63f6-4648-ab1e-ae9155b43e55)
- visiting friends is instantly stopped after the first "Already visited" so this is also already accounted for
- Credit shopping is the only thing that may be done multiple times, but this takes little time and there's the option to "stop purchasing below 300 credits" if you are worried about uselessly spending credits every time.

My answer is from a point of view of full automation. I can give you a personal example.
I have an older laptop which I use as a 24/7 server. After a bit of trial and error I finally managed to get my 4-4-8-8 (24hrs) base rotation. Instead of creating various configs, I just run the "default" all options, except `Auto I.S.`. This way, I don't have to worry about dividing what to do during the reset / non-reset. Sure, this takes a bit more time (total daily) then if I were to use two or even three configs to discriminate reset against non-reset.

If you have more clarifications, I'll be more than happy to answer further questions.

**Comment by wangl-cc** [comment]
I think you can have a look at [maa-cli](https://github.com/MaaAssistantArknights/maa-cli/blob/main/README-EN.md), which is designed for automation. You can have different parameters of task in different conditions, and there is a condition `DayMod` for multi-day cycle. However, it's a command-line tool, so you'll need to edit the configuration file.

**Comment by NyanSequitur** [comment]
> Can't you just make different shifted base plans

I may be stupid, yeah that would work. Will take a look at maa-cli as well. Thanks!
