### ISSUE TITLE
国际服自动肉鸽时到商店会卡住 然后maa会立刻关闭

### ISSUE THREAD

**Issue by ziggyzian** [MaaAssistantArknights/MaaAssistantArknights#8445]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

当使用自动肉鸽功能进行水月肉鸽, 每到商店环节maa会卡住并且自动闪退. 换成其他肉鸽也是一样的结果. 我已重新下载maa及尝试过重启重装等步骤, 都没有作用

### Version

Core Version: v5.1.1-alpha.1.d119.g9b2da02bd
UI Version: v5.1.1-alpha.1.d119.g9b2da02bd
Resource Version: The Black Forest Wills A Dream

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14464701/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14464702/gui.log)
发生问题时间在2月29日全天及3月1日19:41左右(GMT+1)

### 还有别的吗？

MUMU12; windows11

**Comment by Constrat** [comment]
This log only shows March 1st and there is no 19:41.

**Comment by ziggyzian** [comment]
> This log only shows March 1st and there is no 19:41.

It is cuz i deleted the old version maybe. The new log file i believe also contains the problem that ive encountered.

**Comment by Constrat** [comment]
Could I have a timestamp? Logs are very info intensive.

**Comment by ziggyzian** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14465446/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14465451/asst.log)
i have just triggered the bug and this is the new log file. the time i believe is 21:05 (GMT+1)

**Comment by Constrat** [comment]
Log file only shows 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/723b3e49-fadc-44df-a628-3a85e07449b5)
of log...

**Comment by NyanSequitur** [comment]
Here's a log from when it happened to me just now on Mizuki's shop node.
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14466787/asst.log)

Phantom roguelike _also_ consistently crashes after exiting investment menu in store.
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14466699/asst.log)
(these logs are earlier because I was farming Phantom and also consistently crashing in store before I went and tried to reproduce it on Mizuki)

Using nightly build, crash is right at end of log in both cases. Plays normally up until store.

**Comment by Constrat** [comment]
fixed in 19eec57d54f18d2130ef3455fcfc2906e5938b7d (#8524)
