### ISSUE TITLE
[日服] 啟動(startup)出錯

### ISSUE THREAD

**Issue by sniper2824** [MaaAssistantArknights/MaaAssistantArknights#8448]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

查詢過沒有相關issue

本來版本從v4.28一路升級過來, 最近發生startup很慢
就刪除相關檔案並重新下載v5.1.0, 一樣會花超過一分多鐘並出錯

### Version

Core: v5.1.0
模擬器: 夜神 7.0.5.9
OS: Windows 11 22H2 22621.3155

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14467473/debug.zip)

出錯時間點: 
2024-03-02 09:20:38 (開始) 
2024-03-02 09:22:30 (結束)

**Comment by Constrat** [comment]
>  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
Always check the latest nightly before opening issues, this was already fixed in https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/400dc9f42f39a354dab540f3597cae5d2c6204e5 
[alpha/v5.1.1-alpha.1.d118.g999f9087b](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha%2Fv5.1.1-alpha.1.d118.g999f9087b)
