### ISSUE TITLE
YostarEN IS4 开局招募完第一个干员后卡死

### ISSUE THREAD

**Issue by sinyovercosy** [MaaAssistantArknights/MaaAssistantArknights#8632]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽开局时（貌似任意小队或开局干员设置，用百嘉和焰苇都试了几次）选完核心开局6星后就会卡死。
好奇看了一下log，应该是从`Sami@Roguelike@ChooseOperConfirm`之后MAA的操作就变得难以理解了，不知道怎么回事就转到`RecruitSkip`，`RecruitWithoutButton`，然后`DropsFlag`去了。

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.1-alpha.1.d023.g531e169a1
Core Version: v5.2.1-alpha.1.d023.g531e169a1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14622306/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14622307/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24600407/a5b844ff-4d44-4344-9bae-aee318b92772)

### 还有别的吗？

MuMu Player 6 v2.7.23.0 (Windows x64)
电脑配置比较差XD

**Comment by Constrat** [comment]
The `Sami@Roguelike@Recruit.png` score is very low (0.766305).
I also noticed the screen taken (not through Mumu) is 1280x720.
MAA for YostarEN works as expected only in 1920x1080.
If this happened in 1280x720 I highly suggested increasing the resolution to the supported one.
Because of how images and texts are rendered in the global, maintaining multiple resolutions is impossible.

**Comment by Constrat** [comment]
In case you were already on 1920x1080, I'll lower the threshold to 0.75 to patch this.

**Comment by Constrat** [comment]
@sinyovercosy this took a bit of time but I added the change. As said before, I suggest using 1920 instead of 1280.
[a1b9a36](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a1b9a36b23e013f82eb3edb3f741d5f5a6ef9b6f)
