### ISSUE TITLE
CI生成的内测版更新信息使用了用户名称而非用户ID

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#8725]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

表现之一为无法处理空格，因为ID强制不能含有空格，而用户名不限
https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.2.1-alpha.1.d089.g379349d71
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/a829140a-9bef-4d1e-8ef9-a673f58d6a52)

相应的，还有
https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.2.1-alpha.1.d051.gb2a604e7d
用户ID momomochi987 被使用其用户名称呼，指向了错误的用户（HY）

所以此处应该使用用户ID而非用户名
release-nightly-ota.yml line99

### Version

v5.2.1-alpha.1.d089.g379349d71

### 日志文件

无

**Comment by status102** [comment]
这里使用的是提交者的名字，这个名字和Github的应该是没啥关联的（大概？

加上changelog_generator没看懂是怎么解决这个问题的

so help wanted

**Comment by Constrat** [comment]
I've had this happen multiple times even before the nightly changelog update.
What happens is kind of strange. All commits made directly to `dev` (members only) will use the git id that was given in the local configs, meanwhile, if you merge / squash / commit directly from the GitHub interface (website) the "nickname" username will be used.

This happened for example when I squashed the Feat: IS4 EN. Instead of @Constrat, it used @David. Which is my real name that I was using as placeholder in my github account.
To "fix" this the only solution I found was this: 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/3c6e983d-7bad-440c-91a6-d107279ab65a)
