### ISSUE TITLE
⚠️国际服基建宿舍功能异常完成

### ISSUE THREAD

**Issue by Agugu-official** [MaaAssistantArknights/MaaAssistantArknights#8732]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

国际服基建宿舍选人识别错误，每次到宿舍换人会完成任务实际卡在筛选干员界面。（见图）
模拟器显示设置2560*1440 DPI360 165FPS
已附上宿舍最后一次操作模拟器内截图

### Version

Resource Version: Come Catastrophes or Wakes of Vultures
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14811563/debug.zip)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70833021/205148f2-4942-4086-af7c-f938ea9cfb25)
![MuMu12-20240330-184211](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70833021/b60d5f9f-256e-411a-84ad-d366aedc91f9)
![MuMu12-20240330-184231](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70833021/6100cdfc-badd-412c-b3a4-2d2072bad7a7)

### 还有别的吗？

MuMu12 Ver3.8.5(2722)
Windows11 Pro 21H2
Laptop:R9000P 2021 RTX3070

**Comment by Agugu-official** [comment]
补充，当前国际服版本21.1.01（[不义之财](https://prts.wiki/w/%E4%B8%8D%E4%B9%89%E4%B9%8B%E8%B4%A2)）
使用的是默认主题，首页场景是山岳。

**Comment by Constrat** [comment]
> The simulator shows that the setting is 2560*1440 DPI360 165FPS

Not supported, change to 1920x1080

**Comment by Constrat** [comment]
This should fix it:
[02ec5be](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/02ec5be3a2b9db1c4ac649ea6b787952f120c950)

**Comment by Agugu-official** [comment]
> 这应该可以修复它：[02ec5be](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/02ec5be3a2b9db1c4ac649ea6b787952f120c950)

Thank you very much. The problem is solved after replacing the two files. 
(Also, many thanks for understanding those who work with high-resolution environments. This bug is quite simple though XD)

By the way, will there be some functions of MAA that may get disturbed in high-resolution environment? This might be a problem that needs some discussions.

**Comment by Constrat** [comment]
Yes, unfortunately, because of how the text padding is closely related to resolution, heavy ocr tasks may not work as expected.
For example the trader shopping in is, or the operator selection in SSS.

**Comment by Agugu-official** [comment]
> Yes, unfortunately, because of how the text padding is closely related to resolution, heavy ocr tasks may not work as expected. For example the trader shopping in is, or the operator selection in SSS.
> 
> * [AutoSquad Copilot Operator's name Detection in YostarEN #5235](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5235)

I understand. There's no proven solution yet, is there? 🤔

**Comment by Constrat** [comment]
Just for operator detection, no. The solution would be to OCR the operators as close as possible but this introduces possible duplicates etc.
We implemented a while back multiple templates to be recognized, so that could help, but it would need to check every single template if it was working, in case it's not. Screen it from 2560x1440 and add it to the list, radically increasing timings, and reducing performance .

Also, on a side note. The higher the resolution, the heavier everything becomes. MAA downscaled everything to 1280x720, but the emulator needs to run harder when on a lower resolution it wouldn't, leaving more performance for MAA. I choose to adapt everything on 1920x1080 because of a compromise, otherwise I would have gone with 1280x720 as it's to the lowest and less demanding resolution, but after testing, a lot of texts would be too small to be recognized
