### ISSUE TITLE
Not Support Main Menu Themes (BUG)

### ISSUE THREAD

**Issue by ItsukaHiro** [MaaAssistantArknights/MaaAssistantArknights#8864]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

MAA is not support new Main Menu Theme (Both Dark Theme and Chapter 13 Theme):
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64533662/7e80a143-deae-4cca-85e1-5370e87ea55d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64533662/676b9670-e3c6-4ff2-ada1-0a940707b99a)

### Version

v5.2.1

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15039641/asst.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64533662/1801fd29-cde6-4a9d-a790-44e71c7fe4c1)

### Anthing else?

BlueStacks Android 11 (Windows 11)
1920x1080 - 240DPI

**Comment by tmprnc** [comment]
As far as I understand, this is a Global specific problem. CN MAA users already have the other themes working.
There's a good chance they'll have it working eventually.

However, what I do find odd, is that there is no stickied issue regarding this. I would assume it's the sort of issue everyone would complain about.
Also, the easy circumvention is to just use the default theme in the meantime, but I'm also commenting here because I'd like to be pinged when I can start using the other themes; chances are I won't know and just keep going with the white theme.

**Comment by HX3N** [comment]
> As far as I understand, this is a Global specific problem. CN MAA users already have the other themes working. There's a good chance they'll have it working eventually.
> 
> However, what I do find odd, is that there is no stickied issue regarding this. I would assume it's the sort of issue everyone would complain about. Also, the easy circumvention is to just use the default theme in the meantime, but I'm also commenting here because I'd like to be pinged when I can start using the other themes; chances are I won't know and just keep going with the white theme.

You should update to the development version.
As it's already been updated. ec27c418407000648f3ebde07fdfa4e2e31837cb

**Comment by Constrat** [comment]
Instead of pinning, the issue was already resolved two days ago.
When you guys open issues, you click this.
>  I have checked the latest beta update and there is no mention of the bug being fixed.
So when you put 5.2.1 as your version, try and update it before opening the issue. Pinned issues are mainly for issues that are still being worked on.
We can't release full main version every time even for small fixes. Beta and Nightlies are used exactly for this reason

**Comment by tmprnc** [comment]
I was running on the Nightly version. I was unaware that the bug was fixed because when you skip several versions by updating to a more current one, it also skips the older changelog.
