### ISSUE TITLE
更新版本后无法启动MAA

### ISSUE THREAD

**Issue by mc-xx6** [MaaAssistantArknights/MaaAssistantArknights#9321]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA自动更新后无法启动，启动没有任何反应，包括MAA.exe、MAA_v5.exe、MAA_win7.exe、启动旧版.cmd都无法启动MAA，没有任何页面弹出
下载旧版可以打开，但是我无法关闭自动更新

### Version

MAA无法打开，自动更新的信息是：在理智恢复满时推送信息，所以应该是v5.4.0-beta.1

### 日志文件

6月8日
[debug.zip](https://github.com/user-attachments/files/15747376/debug.zip)

**Comment by ABA2396** [comment]
https://t.bilibili.com/940588921739280409#reply225297661584

装一下最新的 .net 8 运行库

**Comment by status102** [comment]
缺少依赖，参照使用说明安装依赖后使用

**Comment by swablueme** [comment]
> https://www.bilibili.com/opus/940613080927174676
> 
> Reference [Documentation](https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98)
Thanks, the bili links fixed my issues. 
Winget has issues
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/10569495/247ebe01-3bc2-4c1e-9ce4-817079e754eb)

**Comment by horror-proton** [comment]
This is likely due to a broken binary compatibility in [vs-2022-17.10](https://github.com/microsoft/STL/releases/tag/vs-2022-17.10).
Vcruntime of GitHub runner image was updated to 17.10 in [win22/20240603.1](https://github.com/actions/runner-images/releases/tag/win22%2F20240603.1), users should also have their vcruntime updated.

https://github.com/microsoft/STL/pull/4339
https://github.com/actions/runner-images/issues/10004
