### ISSUE TITLE
韩服萨米肉鸽不期而遇无法正常选择

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9382]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

具体行为是在所有可选的选项中来回切换但是不确认
（就好像刷出狙击镜和白舞鞋之后你来回点不知道选哪个的样子）

### Version

Resource Version: 시라쿠사인 (재개방)
UI Version: v5.4.0-beta.1.d020.g90d3c140f
Core Version: v5.4.0-beta.1.d020.g90d3c140f

### 日志文件

[asst.txt](https://github.com/user-attachments/files/15831347/asst.txt)
这是一段节选

**Comment by Daydreamer114** [comment]
事件：吉兆

**Comment by Daydreamer114** [comment]
有一个log丢了的是
事件：吉兆

**Comment by Daydreamer114** [comment]
[assts.txt](https://github.com/user-attachments/files/15834988/assts.txt)


[2024-06-14 16:01:52.078] <1><> 关卡: 普通作战
[2024-06-14 16:02:04.358] <1><> 开始战斗: 没有尽头的路
[2024-06-14 16:03:49.007] <1><> 战斗完成
[2024-06-14 16:04:31.989] <1><> 事件: 昏黑之室
[2024-06-14 16:15:07.173] <1><> 正在停止……
[2024-06-14 16:15:07.635] <1><> 已停止
[2024-06-14 16:15:08.929] <1><> Shutdown
[2024-06-14 16:15:08.968] <1><> MaaAssistantArknights GUI exited
[2024-06-14 16:15:08.968] <1><>

**Comment by Daydreamer114** [comment]
[asst.log](https://github.com/user-attachments/files/15835121/asst.log)
[gui.log](https://github.com/user-attachments/files/15835122/gui.log)

**Comment by Daydreamer114** [comment]
事件：雨

识别没做完的话可以搞一个瞎选的模版上来（）

**Comment by Daydreamer114** [comment]
![17201718357572_ pic_hd](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/420558b8-b999-4ac6-bcbc-edfbdf16bba4)

不光是不期而遇，战斗完成之后的也点不上，只要是这种选择的就有可能出问题

**Comment by HX3N** [comment]
I'm not very good at Chinese, so I used a translator. Did I understand it correctly like this?

Is it that the encounter is not being recognized, and even if it is recognized, when choosing an option, it fails to select and keeps repeating the selection process?

I haven't looked at the logs in detail, so I'm not sure, but the issue with option selection could be related to the resolution. Try using a `1920` or `1280` resolution. YoStarKR does not recommend using a `2560` resolution. Other YoStarKR users also found that option selection worked well after changing the resolution.

I just modified it so that "雨" and "有利可图" are now recognized, based on the logs you provided.

**Comment by Daydreamer114** [comment]
yes u understood correctly. maa's behaviour was circular, clicking the third option, then the second, then the first (from bottom to top), but never clicking the confirm button.

maa compress the image to 1280x720 before recognize. i'll try if 1920x1080 or 1280x720 works. thx.

**Comment by Daydreamer114** [comment]
[asst.txt](https://github.com/user-attachments/files/15838316/asst.txt)

这是日服的，看了一眼，score在0.5-0.7左右，可以考虑更新一遍png了

**Comment by Daydreamer114** [comment]
YostarJp with 1920x1080 works well, and YostarKr with 1280x720 works well. im considering update Jp and Kr's images for a better recognition rate this summer.
