### ISSUE TITLE
EN depot export string to Arkplanner needs adjusted (ark-nights site does not import)

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#9672]
### Discussed in https://github.com/orgs/MaaAssistantArknights/discussions/9668

<div type='discussions-op-text'>

<sup>Originally posted by **NanaKG** July 15, 2024</sup>
From what I can tell the export string has English names which breaks the import for the ark-nights site. The import on ark-nights only detects the name in Chinese(except RMA70-12/24, I assume it must be that way on Chinese client?) 

P.S Only know English, Tried search for similar discussions with ArkPlanner(用数据) translated, none of them seemed to mention EN so don't think this EN client problem is mentioned.</div>

**Comment by ABA2396** [comment]
@NanaKG
![image](https://github.com/user-attachments/assets/a63af5ac-8f2e-4781-9db3-86cdf74302f4)

I didn't quite understand what you meant. Can you show me your export result?

**Comment by Constrat** [comment]
I exported this some days ago to https://www.krooster.com/ without any issues whatsoever, directly with "Export to Arkplanner" (which is the Penguin Logistics one)

**Comment by NanaKG** [comment]
My export results. I was saying they do not import into https://ark-nights.com/settings which was one of the links that MAA says should import, because the names of materials are in English instead of Chinese 

{"@type":"@penguin-statistics/depot","items":[{"have":6,"id":"31044","name":"Refined Solvent"},{"have":102,"id":"2004","name":"Strategic Battle Record"},{"have":4,"id":"30115","name":"Polymerization Preparation"},{"have":103,"id":"31043","name":"Semi-Synthetic Solvent"},{"have":25,"id":"mod_unlock_token","name":"Module Data Block"},{"have":112,"id":"2003","name":"Tactical Battle Record"},{"have":14,"id":"2002","name":"Frontline Battle Record"},{"have":85,"id":"30073","name":"Loxic Kohl"},{"have":21,"id":"2001","name":"Drill Battle Record"},{"have":24,"id":"3303","name":"Skill Summary - 3"},{"have":5,"id":"3302","name":"Skill Summary - 2"},{"have":888,"id":"3301","name":"Skill Summary - 1"},{"have":19,"id":"mod_update_token_2","name":"Data Supplement Instrument"},{"have":3,"id":"30014","name":"Orirock Concentration"},{"have":125,"id":"mod_update_token_1","name":"Data Supplement Stick"},{"have":5,"id":"30094","name":"Grindstone Pentahydrate"},{"have":1,"id":"30155","name":"Nucleic Crystal Sinter"},{"have":68,"id":"30053","name":"Aketon"},{"have":5,"id":"30145","name":"Crystalline Electronic Unit"},{"have":272,"id":"30052","name":"Polyketon"},{"have":10,"id":"31073","name":"Fuscous Fiber"},{"have":4,"id":"30135","name":"D32 Steel"},{"have":38,"id":"3262","name":"Medic Chip Pack"},{"have":1,"id":"30125","name":"Bipolar Nanoflake"},{"have":39,"id":"30013","name":"Orirock Cluster"},{"have":12,"id":"31083","name":"Aggregate Cyclicene"},{"have":1,"id":"31064","name":"Transmuted Salt Agglomerate"},{"have":36,"id":"31063","name":"Transmuted Salt"},{"have":23,"id":"30062","name":"Device"},{"have":18,"id":"31054","name":"Cutting Fluid Solution"},{"have":95,"id":"31053","name":"Compound Cutting Fluid"},{"have":808,"id":"30012","name":"Orirock Cube"},{"have":169,"id":"31033","name":"Crystalline Component"},{"have":94,"id":"30063","name":"Integrated Device"},{"have":5,"id":"31024","name":"Incandescent Alloy Block"},{"have":4,"id":"30064","name":"Optimized Device"},{"have":56,"id":"31023","name":"Incandescent Alloy"},{"have":2,"id":"30084","name":"Manganese Trihydrate"},{"have":2,"id":"31014","name":"Polymerized Gel"},{"have":88,"id":"30083","name":"Manganese Ore"},{"have":99,"id":"31013","name":"Coagulating Gel"},{"have":18,"id":"3232","name":"Defender Chip Pack"},{"have":3,"id":"30074","name":"White Horse Kohl"},{"have":461,"id":"30031","name":"Ester"},{"have":30,"id":"30093","name":"Grindstone"},{"have":34,"id":"30103","name":"RMA70-12"},{"have":345,"id":"30011","name":"Orirock"},{"have":235,"id":"30042","name":"Oriron"},{"have":76,"id":"30033","name":"Polyester Pack"},{"have":88,"id":"30061","name":"Damaged Device"},{"have":35,"id":"30043","name":"Oriron Cluster"},{"have":15,"id":"32001","name":"Chip Catalyst"},{"have":239,"id":"30032","name":"Polyester"},{"have":25,"id":"30024","name":"Sugar Lump"},{"have":4,"id":"3271","name":"Supporter Chip"},{"have":10,"id":"3222","name":"Guard Chip Pack"},{"have":83,"id":"30023","name":"Sugar Pack"},{"have":252,"id":"30022","name":"Sugar"},{"have":418,"id":"30021","name":"Sugar Substitute"},{"have":1,"id":"30044","name":"Oriron Block"},{"have":341,"id":"30041","name":"Oriron Shard"},{"have":3,"id":"30054","name":"Keton Colloid"},{"have":253,"id":"30051","name":"Diketon"},{"have":4,"id":"3273","name":"Supporter Dualchip"},{"have":6,"id":"3242","name":"Sniper Chip Pack"},{"have":25,"id":"3252","name":"Caster Chip Pack"},{"have":8,"id":"3272","name":"Supporter Chip Pack"},{"have":36,"id":"3282","name":"Specialist Chip Pack"},{"have":16,"id":"3211","name":"Vanguard Chip"},{"have":7,"id":"3231","name":"Defender Chip"},{"have":24,"id":"3251","name":"Caster Chip"},{"have":19,"id":"3281","name":"Specialist Chip"}]}

**Comment by ABA2396** [comment]
I checked, and the standard format distinguishes materials by ID. I will provide feedback to .Houdou
![image](https://github.com/user-attachments/assets/f9302aaf-f1a6-4552-8844-747408635ad5)

**Comment by Constrat** [comment]
Arkntools seems the most simple one as it's literally "id": quantity.
```
{"2001":10500,"2002":2667,"2003":1372,"2004":85,"30011":1386,"30012":7450,"30013":73,"30014":19,"30021":921,"30022":1763,"30023":218,"30024":37,"30031":871,"30032":1297,"30033":673,"30034":26,"30041":518,"30042":1505,"30043":629,"30044":28,"30051":677,"30052":1322,"30053":609,"30054":39,"30061":396,"30062":1300,"30063":731,"30064":29,"30073":732,"30083":593,"30084":34,"30093":472,"30094":33,"30103":624,"30104":42,"30115":2,"30135":2,"30145":4,"30155":12,"31013":534,"31014":19,"31023":775,"31024":3,"31033":654,"31034":25,"31043":497,"31044":33,"31053":667,"31054":15,"31063":266,"31064":39,"31073":99,"31074":7,"31083":70,"31084":8,"32001":1,"3211":55,"3212":33,"3221":15,"3222":24,"3231":78,"3232":34,"3241":35,"3242":42,"3251":54,"3252":63,"3261":84,"3262":32,"3271":30,"3272":42,"3281":57,"3282":77,"3301":6057,"3302":3722,"3303":1011,"mod_unlock_token":265,"mod_update_token_1":2365,"mod_update_token_2":658}
```

**Comment by ABA2396** [comment]
cc @Houdou

**Comment by Constrat** [comment]
Fixed with https://github.com/Houdou/arkgraph/commit/f5c72f5a5482c6e8ad9d165f5e4262f995537b91

**Comment by Houdou** [comment]
🤣 Found a bug years ago on the importing logic.
For all these years, it was relying on the fallback of matching by name, LOL
