### ISSUE TITLE
肉鸽尝试继续探索而不是直接放弃

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#9897]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在从 非肉鸽道中界面 开始“自动肉鸽”时，会直接点击放弃探索，而很多（我遇到的）情况是因某些其他原因暂停了肉鸽等（比如修改了一些设置）导致暂时退出了肉鸽界面

### 有什么好的想法？

尝试点击继续探索，然后就像在道中开始可以自动继续那样

### 其他内容

感谢各位开发者🌹

**Comment by Saratoga-Official** [comment]
放弃探索通常是maa没有识别到下一个节点造成的，你可以卡在一个合适位置点maa开始，或者点开关卡详情，总之你得进去再点开始

**Comment by Constrat** [comment]
^ Above comment is correct. Plus there's one more reason.

When MAA starts a run from zero, it will keep count of various parameters, such which operators have been recruited, what foldartals have been unlocked etc. 

So even if MAA can correctly continue a run, don't expect it to be as good as a fully restarted one.

**Comment by KJH-x** [comment]
理解

**Comment by Daydreamer114** [comment]
> ^ Above comment is correct. Plus there's one more reason.
> 
> When MAA starts a run from zero, it will keep count of various parameters, such which operators have been recruited, what foldartals have been unlocked etc.
> 
> So even if MAA can correctly continue a run, don't expect it to be as good as a fully restarted one.

He means starting the task in this interface will give up the explore.
![MuMu12-20240728-123133](https://github.com/user-attachments/assets/3a654de3-932e-49fb-b1c0-04058a5f0f20)

That may because the priority of recognizing give up is higher than continue the explore.
![image](https://github.com/user-attachments/assets/aeb49040-a573-4d71-80e7-4a0290f944b9)

I'm for him, which I also think that promoting the priority of "Roguelike@Continue" is better.

**Comment by ABA2396** [comment]
放弃重开的逻辑是怎么样的，这样改了之后会放弃不了吗

**Comment by Daydreamer114** [comment]
> 放弃重开的逻辑是怎么样的，这样改了之后会放弃不了吗

不会，这个begin应该是肉鸽启动的入口，这么改也只执行一次

**Comment by ABA2396** [comment]
试了下没问题，应该可以

**Comment by KJH-x** [comment]
已经修复的问题为啥close as not planned（？）

**Comment by status102** [comment]
> 已经修复的问题为啥close as not planned（？）

因为关闭本issue的提交已回滚
